# Generated by Django 5.1.6 on 2025-05-20 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0002_formations_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdata.projects')),
                ('Technologies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdata.technologies')),
            ],
        ),
    ]
