# Generated by Django 5.1.6 on 2025-05-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0003_tech_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='paye',
            field=models.BooleanField(default=False),
        ),
    ]
