# Generated by Django 5.1.6 on 2025-05-23 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0004_participation_paye'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formations',
            name='Heure',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='formations',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='formations',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('user', 'formation')},
        ),
    ]
