# Generated by Django 5.1.6 on 2025-05-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0005_formations_heure_formations_place_formations_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='attestation',
            field=models.FileField(null=True, upload_to='attestation'),
        ),
    ]
