# Generated by Django 5.1.6 on 2025-05-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0006_participation_attestation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formations',
            old_name='Heure',
            new_name='heure',
        ),
    ]
